### PR TITLE
Output archives instead of individual files

### PR DESCRIPTION
**Pull request by shwnchpl**
This patch alters the behavior of gpu-trace to output a single zip archive containing all trace/capture files rather than individual files.

### CODE REVIEW

**Comment by shwnchpl** [comment]
@lostgoat, have you had a chance to take a look at this yet?

**Comment by lostgoat** [comment]
Looks good. If I'm reading the commit correctly then opening gpuvis automatically with an old version of gpuvis will fail since it might not have zip support.

That should be fine. But it would be good to record the version requirements in the commit message.

**Comment by lostgoat** [comment]
I invited you as a collaborator so that you can merge this commit once you make the necessary changes.

**Comment by shwnchpl** [comment]
Updated and merged!  Thanks! :smiley:

**Pull request merged**
